export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const ORDER_BURGER = 'ORDER_BURGER';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
export const ORDER_BURGER_START_LOAD = 'ORDER_BURGER_START_LOAD';
export const ORDER_INIT = 'ORDER_INIT';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_INIT = ' AUTH_INIT';
export const AUTH = ' AUTH';
export const AUTH_FAILED = ' AUTH_FAILED';
export const AUTH_RESET_ERROR = ' AUTH_RESET_ERROR';  //for error message in between register and login pages
export const AUTH_LOGOUT = ' AUTH_LOGOUT';
export const AUTH_SET_REDIRECT = 'AUTH_SET_REDIRECT';